id: SoftSort-KL
pretrained: null
seed: 3698
model:
    # name: BaseClassifier
    # args:
    #     extractor_cfg: 
    #         name: ResNetExtractor
    #         args:
    #             version: resnet18
    #     nclasses: 10
    name: CNN
    args:
        hidden: 64
        nclasses: 10
optimizer:
    name: Adam
    args:
        lr: 0.0001
loss:
    name: TopKClassificationLoss
    args:
        nclasses: 10
        regularization: kl
        regularization_strength: 1.0
metric:
    - name: Accuracy
      args:
    - name: TopK
      args:
        k: 3
        nclasses: 10
scheduler:
    name: ReduceLROnPlateau
    args:
        mode: min
        factor: 0.5
        patience: 10000
        verbose: True
dataset:
    train:
        name: CIFARDataset
        args:
            is_train: True
        loader:
            name: DataLoader
            args:
                batch_size: 1024
                shuffle: True
                pin_memory: True
    val:
        name: CIFARDataset
        args:
            is_train: False
        loader:
            name: DataLoader
            args:
                batch_size: 1024
                shuffle: False
                pin_memory: True
trainer:
    nepochs: 500
    val_step: 1
    log_step: 1
    log_dir: runs